#!/usr/bin/env python3
"""Complete Migrations Example: Full Migration Workflow with DeeBase.

This example demonstrates the complete migration lifecycle using both
CLI commands and Python API. It shows:
- Creating migration files
- Applying migrations with `migrate up`
- Rolling back with `migrate down`
- Database backups with `db backup`
- Version tracking and status

Run with: uv run examples/complete_migrations_example.py
"""

import subprocess
import tempfile
import sys
from pathlib import Path


def run_cmd(cmd: str, cwd: str, check: bool = True) -> str:
    """Run a CLI command and return output."""
    full_cmd = f"uv run deebase {cmd}"
    result = subprocess.run(
        full_cmd,
        shell=True,
        cwd=cwd,
        capture_output=True,
        text=True,
    )
    if check and result.returncode != 0:
        print(f"Command failed: {full_cmd}")
        print(f"stderr: {result.stderr}")
        print(f"stdout: {result.stdout}")
        sys.exit(1)
    return result.stdout + result.stderr


def main():
    print("=" * 70)
    print("DeeBase Complete Migrations Example")
    print("=" * 70)

    with tempfile.TemporaryDirectory() as tmpdir:
        print(f"\nWorking in: {tmpdir}\n")

        # ================================================================
        # STEP 1: Initialize the project
        # ================================================================
        print("STEP 1: Initialize DeeBase Project")
        print("-" * 50)
        print("$ deebase init")
        output = run_cmd("init", tmpdir)
        print(output)

        # ================================================================
        # STEP 2: Create migration files manually
        # ================================================================
        print("\n" + "=" * 70)
        print("STEP 2: Create Migration Files")
        print("-" * 50)

        migrations_dir = Path(tmpdir) / "migrations"

        # Migration 1: Create users table
        migration1 = '''"""Migration: Create users table

Auto-generated by deebase CLI.
"""

from deebase import Database


async def upgrade(db: Database):
    """Apply this migration."""
    await db.q("""
        CREATE TABLE users (
            id INTEGER PRIMARY KEY,
            name TEXT NOT NULL,
            email TEXT UNIQUE,
            status TEXT DEFAULT 'active'
        )
    """)


async def downgrade(db: Database):
    """Reverse this migration."""
    await db.q("DROP TABLE users")
'''
        (migrations_dir / "0001-create-users.py").write_text(migration1)
        print("Created: migrations/0001-create-users.py")

        # Migration 2: Create posts table
        migration2 = '''"""Migration: Create posts table

Auto-generated by deebase CLI.
"""

from deebase import Database


async def upgrade(db: Database):
    """Apply this migration."""
    await db.q("""
        CREATE TABLE posts (
            id INTEGER PRIMARY KEY,
            author_id INTEGER REFERENCES users(id),
            title TEXT NOT NULL,
            content TEXT,
            views INTEGER DEFAULT 0
        )
    """)
    await db.q("CREATE INDEX ix_posts_author ON posts(author_id)")


async def downgrade(db: Database):
    """Reverse this migration."""
    await db.q("DROP INDEX ix_posts_author")
    await db.q("DROP TABLE posts")
'''
        (migrations_dir / "0002-create-posts.py").write_text(migration2)
        print("Created: migrations/0002-create-posts.py")

        # Migration 3: Create comments table
        migration3 = '''"""Migration: Create comments table

Auto-generated by deebase CLI.
"""

from deebase import Database


async def upgrade(db: Database):
    """Apply this migration."""
    await db.q("""
        CREATE TABLE comments (
            id INTEGER PRIMARY KEY,
            post_id INTEGER REFERENCES posts(id),
            user_id INTEGER REFERENCES users(id),
            body TEXT NOT NULL,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
    """)


async def downgrade(db: Database):
    """Reverse this migration."""
    await db.q("DROP TABLE comments")
'''
        (migrations_dir / "0003-create-comments.py").write_text(migration3)
        print("Created: migrations/0003-create-comments.py")

        # ================================================================
        # STEP 3: Check migration status (before applying)
        # ================================================================
        print("\n" + "=" * 70)
        print("STEP 3: Check Migration Status (Before)")
        print("-" * 50)
        print("$ deebase migrate status")
        output = run_cmd("migrate status", tmpdir)
        print(output)

        # ================================================================
        # STEP 4: Apply all migrations
        # ================================================================
        print("\n" + "=" * 70)
        print("STEP 4: Apply All Migrations")
        print("-" * 50)
        print("$ deebase migrate up")
        output = run_cmd("migrate up", tmpdir)
        print(output)

        # ================================================================
        # STEP 5: Check status after applying
        # ================================================================
        print("\n" + "=" * 70)
        print("STEP 5: Check Migration Status (After)")
        print("-" * 50)
        print("$ deebase migrate status")
        output = run_cmd("migrate status", tmpdir)
        print(output)

        # ================================================================
        # STEP 6: Verify tables were created
        # ================================================================
        print("\n" + "=" * 70)
        print("STEP 6: Verify Tables Were Created")
        print("-" * 50)
        print("$ deebase table list")
        output = run_cmd("table list", tmpdir)
        print(output)

        # ================================================================
        # STEP 7: Insert sample data
        # ================================================================
        print("\n" + "=" * 70)
        print("STEP 7: Insert Sample Data")
        print("-" * 50)

        run_cmd("sql \"INSERT INTO users (name, email) VALUES ('Alice', 'alice@example.com')\" --no-record", tmpdir)
        run_cmd("sql \"INSERT INTO users (name, email) VALUES ('Bob', 'bob@example.com')\" --no-record", tmpdir)
        run_cmd("sql \"INSERT INTO posts (author_id, title, content, views) VALUES (1, 'Hello World', 'First post!', 100)\" --no-record", tmpdir)
        run_cmd("sql \"INSERT INTO posts (author_id, title, content, views) VALUES (2, 'Bobs Post', 'Another post', 50)\" --no-record", tmpdir)
        run_cmd("sql \"INSERT INTO comments (post_id, user_id, body) VALUES (1, 2, 'Great post!')\" --no-record", tmpdir)
        print("Sample data inserted.")

        print("\n$ deebase sql \"SELECT * FROM users\" --no-record")
        output = run_cmd("sql \"SELECT * FROM users\" --no-record", tmpdir)
        print(output)

        # ================================================================
        # STEP 8: Create a database backup
        # ================================================================
        print("\n" + "=" * 70)
        print("STEP 8: Create Database Backup")
        print("-" * 50)
        print("$ deebase db backup")
        output = run_cmd("db backup", tmpdir)
        print(output)

        # Show backup files
        data_dir = Path(tmpdir) / "data"
        backups = list(data_dir.glob("*.backup"))
        if backups:
            print(f"Backup created: {backups[0].name}")
            print(f"Size: {backups[0].stat().st_size} bytes")

        # ================================================================
        # STEP 9: Rollback last migration
        # ================================================================
        print("\n" + "=" * 70)
        print("STEP 9: Rollback Last Migration")
        print("-" * 50)
        print("$ deebase migrate down -y")
        output = run_cmd("migrate down -y", tmpdir)
        print(output)

        # Verify comments table was dropped
        print("\n$ deebase table list")
        output = run_cmd("table list", tmpdir)
        print(output)

        # ================================================================
        # STEP 10: Check status after rollback
        # ================================================================
        print("\n" + "=" * 70)
        print("STEP 10: Check Migration Status (After Rollback)")
        print("-" * 50)
        print("$ deebase migrate status")
        output = run_cmd("migrate status", tmpdir)
        print(output)

        # ================================================================
        # STEP 11: Apply migrations up to version 3 again
        # ================================================================
        print("\n" + "=" * 70)
        print("STEP 11: Re-apply Migrations Up to Version 3")
        print("-" * 50)
        print("$ deebase migrate up --to 3")
        output = run_cmd("migrate up --to 3", tmpdir)
        print(output)

        # ================================================================
        # STEP 12: Rollback to version 1
        # ================================================================
        print("\n" + "=" * 70)
        print("STEP 12: Rollback to Version 1")
        print("-" * 50)
        print("$ deebase migrate down --to 1 -y")
        output = run_cmd("migrate down --to 1 -y", tmpdir)
        print(output)

        # Check what's left
        print("\n$ deebase table list")
        output = run_cmd("table list", tmpdir)
        print(output)

        print("\n$ deebase migrate status")
        output = run_cmd("migrate status", tmpdir)
        print(output)

        # ================================================================
        # STEP 13: Apply all again to finish
        # ================================================================
        print("\n" + "=" * 70)
        print("STEP 13: Apply All Migrations Again")
        print("-" * 50)
        print("$ deebase migrate up")
        output = run_cmd("migrate up", tmpdir)
        print(output)

        # ================================================================
        # STEP 14: Final database info
        # ================================================================
        print("\n" + "=" * 70)
        print("STEP 14: Final Database Info")
        print("-" * 50)
        print("$ deebase db info")
        output = run_cmd("db info", tmpdir)
        print(output)

        # ================================================================
        # Summary
        # ================================================================
        print("\n" + "=" * 70)
        print("Migration Workflow Summary")
        print("=" * 70)
        print("""
Commands demonstrated:

  deebase init              - Initialize project with migrations/ directory
  deebase migrate status    - Show current migration state
  deebase migrate up        - Apply all pending migrations
  deebase migrate up --to N - Apply migrations up to version N
  deebase migrate down -y   - Rollback last migration (skip prompt)
  deebase migrate down --to N - Rollback to version N
  deebase db backup         - Create timestamped backup

Migration file format: NNNN-description.py
  - upgrade(db) - Apply changes
  - downgrade(db) - Rollback changes

Version tracking: _deebase_migrations table
  - Records version, name, applied_at timestamp
  - Prevents re-applying already-applied migrations
""")


if __name__ == "__main__":
    main()
